(function (root, factory) {
    const api = factory();
    if (typeof module === 'object' && module.exports) module.exports = api;
    else root.StashStateStore = api;
}(typeof globalThis !== 'undefined' ? globalThis : this, function () {
    'use strict';

    function createStateStore() {
        return {
            token: '',
            adminToken: '',
            isAdmin: false,
            adminChecked: false,
            adminLoading: false,
            maintenanceAction: false,
            adminError: '',
            maintenance: { model: '', dimensions: 0, episodes_total: 0, facts_total: 0, episodes_pending: 0, facts_pending: 0, pending: 0, due: 0, failed: 0, latest_error: '' },
            sessionId: '',
            requestId: 0,
            auth: { auth_mode: 'none', authenticated: false, user: '' },
            authChecked: false,
            authLoading: true,
            authError: '',
            result: 'Stash 콘솔입니다.\n\n왼쪽 메뉴에서 작업이나 기억을 선택하세요.',
            resultValue: null,
            resultKind: '',
            resultTitle: '결과',
            resultDescription: '선택한 항목의 응답을 표시합니다.',
            loading: false,
            notice: { text: '', type: 'success' },
            lastLoadedAt: null,
            noticeTimer: null,
            view: 'goal-map',
            activeNav: 'goal-map',
            tokenOpen: false,
            pageSize: 50,
            listPage: { tool: '', args: {}, offset: 0, nextOffset: 0, limit: 50, hasNext: false, history: [] },
            listError: '',
            boardPage: { offset: 0, nextOffset: 0, limit: 50, hasNext: false, history: [] },
            worktreePage: { offset: 0, nextOffset: 0, limit: 50, hasNext: false, history: [] },
            commentPage: { offset: 0, nextOffset: 0, limit: 50, hasNext: false, history: [] },
            draggedItem: null,
            boardError: '',
            boardFilter: { q: '', issueType: '', label: '' },
            issueFormOpen: false,
            issueForm: { title: '', description: '', issueType: 'task', labels: '' },
            selectedIssue: null,
            selectedComments: [],
            selectedMemoryLinks: [],
            commentBody: '',
            copyStatus: '복사',
            agentGuide: [
                '# Stash Work Plan Convention',
                '',
	                    'Maintain the Stash goal and work map as the shared AI execution record. Human work may remain authoritative in Jira, Confluence, or another external system. Git and external connectors are optional.',
	                    '',
	                    'If the `stash-work-plan` skill is installed, load it before changing plan state. It contains the MCP workflow and the same convention described here.',
	                    '',
	                    '## Work execution continuity',
	                    '',
	                    '- Call `resume_project(namespace, agent_id, capabilities)` at session start. It requires no local path, Git repository, or MCP Roots.',
	                    '- Keep `context_digest` and send it as `known_context_digest` on later resume calls. Use `detail: full` only for a specific missing record.',
	                    '- Continue active work first. Otherwise choose one of the returned ready items whose `required_capabilities` you can satisfy.',
	                    '- Call `resume_work` for that item. Read its goal path, parent plan component, owned scopes, and next action, then call `claim_work` immediately before acting.',
	                    '- Keep the returned `lease_token` private. Never bypass another live lease or create replacement work because the previous chat is unavailable.',
	                    '- Call `checkpoint_work` after each meaningful action with the observed result and exactly one concrete `next_action`.',
	                    '- Use `spawn_work` when the current task reveals a child or prerequisite. It prepares the new item and links it to the current task atomically.',
	                    '- Submit observable results with `submit_work_evidence`, link them to the relevant condition, and call `verify_work_condition`.',
	                    '- Call `finish_work` only after every required condition has accepted evidence and every blocker is finished.',
	                    '- Before stopping unfinished work, call `handoff_work`. A fresh agent resumes from the same work item ID and its recorded next action.',
	                    '',
	                    '## Shared outcome tree',
	                    '',
	                    '- Treat the selected top-level goal as the project outcome. A-1, A-2, and deeper results are child goals that combine into it.',
	                    '- Read `goal_context.path` and `plan_context` before acting. Attach each component or task to the narrowest matching goal with `goal_id`.',
	                    '- Do not start detached work or work assigned outside the shared tree. A start or claim returns the same compact goal path.',
	                    '- Link only durable context, constraints, decisions, failures, evidence, and results. Omit routine narration.',
	                    '- Verified leaf work completes eligible child and parent goals. Never complete a parent while child work remains unfinished.',
	                    '',
                '## Component map',
                '',
                '- Plan nodes are **components of the system being built**, not phases, sprints, or a chronological to-do list. Create them with `create_plan_component`.',
	                    '- Create one component for each independently owned part of the system. Put executable work in child tasks.',
                '- A component\'s `issue_key` is its stable identifier. Do not reuse it for a different component. Add or remove nodes instead of changing their identity.',
	                    '- Use `update_plan_component` to clarify a component\'s wording, completion condition, implementation note, or owned scope without changing its stable identity.',
                '- Use `delete_plan_component` or `delete_plan_task` to remove an obsolete node. Do not recycle it by changing its purpose.',
                '- Titles are verb-led, plain-language, and concrete enough for the owner to recognize completion. Prefer `Read alerts out loud` over `Audio pipeline`, and never use vague labels such as `Decide what matters`.',
                '- Put implementation wording in `technical_details`, not in the title. Put the owner-facing scope and done condition in `description`.',
                '',
                '## Tasks and live state',
                '',
	                    '- Create executable child tasks with `create_plan_task`, its `component_id`, and the narrowest matching `goal_id`. A component is the map; its tasks are the work.',
	                    '- Use `update_plan_task` when a task\'s outcome, completion condition, implementation note, or provenance needs clarification. It keeps the component, issue key, state, agents, and worktree links intact.',
                '- Map task state as follows: `ready` is not started, `doing` is in progress, `done` is complete, and `blocked` is stuck. Use `review` only when the owner explicitly needs a review state.',
	                    '- Prepare completion conditions and call `claim_work` before acting. It records `doing`, the task owner, and immutable starter data together.',
	                    '- Call `finish_work` the moment the verified task is complete. If work is stuck, checkpoint the blocker, hand off the active attempt, and then use `block_plan_task`.',
                '- Never batch plan updates at the end of a session. Every state change is an API write when it happens.',
                '- For an open task, set `provenance` to `agent` when an agent is declaring its imminent build intent, or `roadmap` when the task comes from durable planning material. Leave it empty only when neither is true.',
                '',
                '## Dependencies and linked resources',
                '',
                '- Connect components with `link_plan_components`. `needs` means the component must come after the related component; `links` means the two components are connected. The underlying `blocks` edge remains directed.',
                '- Add required routing hints with `set_work_capabilities`; these hints never grant authorization.',
	                    '- Use `attach_work_resource` for Jira issues, Confluence pages, Git checkouts, documents, browser targets, APIs, datasets, devices, and result artifacts.',
	                    '- Keep external bodies and credentials in their original system. Store only a short summary, stable key, revision, and URI in Stash.',
	                    '- Git users may optionally use `resolve_workspace`, `resume_workspace`, and `claim_workspace`; other work never needs them.',
                '',
                '## Decisions and evidence',
                '',
                '- Record a plan-affecting decision with `record_plan_decision` **before** implementing it. Attach it to the affected component or task when possible.',
                '- Attach evidence and lessons with `link_work_item_memory`; inspect it with `list_work_item_memory_links`.',
	                    '- Use `add_work_item_comment` for handoff details, reproduction notes, and decisions that do not change the plan itself.',
	                    '',
	                    '## Semantic review',
	                    '',
	                    '- `get_work_plan` returns deterministic convention warnings without calling a model. Resolve those warnings directly.',
	                    '- Call `validate_work_plan` after meaningful component, task, dependency, or decision changes and before handing off the plan. It uses the configured Reasoner model, not the embedding model.',
	                    '- Treat model findings as review advice. Fix supported component findings with `update_plan_component` and task findings with `update_plan_task`, then run `validate_work_plan` again.',
	                    '- If `get_work_plan.validation.stale` is true, the saved review predates the current plan. Run it again before relying on the result.',
	                    '- If a list response contains `has_more: true`, call the same tool again with `offset` set to its `next_offset`. Keep each chunk separate instead of combining every page into one prompt.',
	                    '- A plan review does not replace builds, tests, or observing the product.',
	                    '',
	                    '## Session start and end',
                '',
	                    '1. Call `resume_project` with the exact project namespace and your capabilities.',
	                    '2. Resume active work or select one returned candidate, then call `resume_work`.',
	                    '3. Run `validate_work_plan` when the plan meaning changed or its saved validation is stale.',
	                    '4. Before ending an active attempt, either finish it with verified evidence or call `handoff_work` with one concrete next action. Save durable facts with `remember_work`.',
                '',
                'Use `create_work_item` for ad-hoc local bugs, questions, and tracker entries that do not belong in the component map. Use the plan API for the owner-facing plan; do not maintain a separate live `PLAN.md` alongside it.'
            ].join('\n'),
            boardColumns: [
                { status: 'backlog', label: '대기' },
                { status: 'ready', label: '준비' },
                { status: 'doing', label: '진행 중' },
                { status: 'blocked', label: '막힘' },
                { status: 'review', label: '검토' },
                { status: 'done', label: '완료' },
                { status: 'canceled', label: '취소' }
            ],
        };
    }

    return { createStateStore };
}));
