(function (root) {
    'use strict';
    const template = `
<section v-if="authLoading || !authChecked || needsLogin" class="stash-login" :aria-label="t('auth.login')">
  <div class="stash-login-card"><div class="stash-brand"><span class="stash-brand-mark">S</span><span>Stash</span></div>
    <div class="stash-login-language"><select class="stash-language-select" :aria-label="t('language.label')" :value="locale" @change="changeLocale($event.target.value)"><option value="ko">한국어</option><option value="en">English</option></select></div>
    <p v-if="authLoading" role="status">{{ t('auth.checking') }}</p>
    <template v-else-if="!authChecked"><p class="stash-error" role="alert">{{ t(error) }}</p><button type="button" class="stash-button" @click="bootstrap">{{ t('action.retry') }}</button></template>
    <template v-else><h1>{{ t('auth.heading') }}</h1><a class="stash-button is-primary" href="/auth/login" @click.prevent="beginLogin">{{ t('auth.login') }}</a></template>
  </div>
</section>
<div v-else class="stash-console" @keydown.esc="route.detail ? closeDetail() : clearSelection()">
  <aside class="stash-sidebar" :aria-label="t('nav.main')">
    <div class="stash-brand"><span class="stash-brand-mark">S</span><span>Stash</span></div>
    <label class="stash-root-select"><span>{{ t('nav.workspaces') }}</span><select v-model="rootSlug" :title="rootSlug" @change="changeRoot"><option v-for="item in rootOptions" :key="item.slug" :value="item.slug">{{ item.name || (item.slug === '/' ? t('workspace.default') : item.slug) }}</option></select></label>
    <select class="stash-mobile-nav" :aria-label="t('nav.page')" :value="route.route" @change="navigate($event.target.value)"><option v-for="item in navItems" :key="item.route" :value="item.route">{{ item.label }}</option><option value="list_memories">{{ t('nav.memories') }}</option><option value="list_goals">{{ t('nav.goals') }}</option><option value="list_namespaces">{{ t('nav.manageWorkspaces') }}</option><option value="agent">{{ t('nav.agent') }}</option><option value="maintenance">{{ t('nav.maintenance') }}</option></select>
    <nav class="stash-nav">
      <span class="stash-nav-label">{{ t('nav.project') }}</span>
      <a v-for="item in navItems" :key="item.route" :href="navHref(item.route)" :class="{'is-active': route.route === item.route}" :aria-current="route.route === item.route ? 'page' : null" @click.prevent="navigate(item.route)"><span class="stash-nav-icon">{{ item.icon }}</span><span>{{ item.label }}</span></a>
      <a :href="navHref('list_goals')" :class="{'is-active': route.route === 'list_goals'}" @click.prevent="navigate('list_goals')"><span class="stash-nav-icon">↗</span><span>{{ t('nav.goals') }}</span></a>
      <a :href="navHref('list_memories')" :class="{'is-active': ['list_memories', 'query_facts', 'list_hypotheses'].includes(route.route)}" @click.prevent="navigate('list_memories')"><span class="stash-nav-icon">✓</span><span>{{ t('nav.memories') }}</span></a>
    </nav>
    <div class="stash-sidebar-foot"><a :href="navHref('list_namespaces')" :class="{'is-active': route.route === 'list_namespaces'}" @click.prevent="navigate('list_namespaces')"><span class="stash-nav-icon">◌</span><span>{{ t('nav.manageWorkspaces') }}</span></a><a :href="navHref('agent')" @click.prevent="navigate('agent')">{{ t('nav.agent') }}</a><a :href="navHref('maintenance')" @click.prevent="navigate('maintenance')">{{ t('nav.maintenance') }}</a></div>
    <div class="stash-sidebar-settings">
      <label><span>{{ t('theme.label') }}</span><select class="stash-theme-select" :value="themePreference" @change="changeTheme($event.target.value)"><option value="system">{{ t('theme.system') }}</option><option value="light">{{ t('theme.light') }}</option><option value="dark">{{ t('theme.dark') }}</option></select></label>
      <label><span>{{ t('language.label') }}</span><select class="stash-language-select" :value="locale" @change="changeLocale($event.target.value)"><option value="ko">한국어</option><option value="en">English</option></select></label>
    </div>
  </aside>

  <main class="stash-main">
    <header class="stash-topbar">
      <div><h1>{{ pageTitle }}</h1></div>
      <div class="stash-top-actions">

        <a v-if="canLogin && !auth.authenticated" class="stash-button is-primary" href="/auth/login" @click.prevent="beginLogin">{{ t('auth.login') }}</a>
        <button v-else-if="auth.authenticated" type="button" class="stash-button" :aria-expanded="authPanelOpen" aria-controls="stash-account" @click="authPanelOpen = !authPanelOpen">{{ t('auth.account') }}</button>
        <button type="button" class="stash-button" :disabled="loading" @click="loadRoute()" :aria-label="t('action.refresh')" :title="t('action.refresh')">↻</button>
      </div>
    </header>

    <section v-if="authPanelOpen" id="stash-account" class="stash-token-panel" @keydown.esc="authPanelOpen = false">
      <div class="stash-inspector-head"><h3>{{ t('auth.account') }}</h3><button type="button" :aria-label="t('auth.closeAccount')" @click="authPanelOpen = false">×</button></div>
      <div class="stash-token-actions"><button type="button" class="stash-button" :disabled="tokenLoading" @click="issueToken">{{ tokenLoading ? t('auth.issuing') : t('auth.issueToken') }}</button><a class="stash-button is-quiet" href="/auth/logout" @click.prevent="logout">{{ t('auth.logout') }}</a></div>
      <div class="stash-token-issued" v-if="issuedToken"><code>{{ issuedToken }}</code><button type="button" class="stash-button" @click="copyIssuedToken">{{ t('auth.copyToken') }}</button></div>
      <div v-if="tokenError" class="stash-error">{{ t(tokenError) }}</div>
    </section>

    <section class="stash-surface">
      <div v-if="error" class="stash-error" role="alert">{{ t(error) }} <button type="button" class="stash-button" @click="loadRoute()">{{ t('action.retry') }}</button> <button v-if="['goal-map', 'monitor'].includes(route.route)" type="button" class="stash-button" @click="navigate('board')">{{ t('view.workList') }}</button></div>
      <div v-if="loading" class="stash-loading" role="status">{{ t('view.loading') }}</div>
      <div v-else-if="!error" class="stash-content-grid" :class="{'has-inspector': selected && !route.detail}">
        <div v-if="contextError" class="stash-context-note" role="status">{{ t(contextError) }}</div>
        <div v-if="!route.detail && (map.resources_truncated || graph.has_more)" class="stash-context-note">{{ t('view.partial') }}</div>
        <section>
          <article v-if="route.detail && selected" class="stash-detail" tabindex="-1">
            <header><div><p class="stash-kicker">{{ t('view.detailTitle', { kind: kindLabel(selected.kind) }) }}</p><h2>{{ selectedTitle }}</h2></div><button type="button" class="stash-button" @click="closeDetail">{{ t('action.backToList') }}</button></header>
            <p v-if="detailLoading" role="status">{{ t('view.loadingOriginal') }}</p><p v-if="detailError" class="stash-error" role="alert">{{ t(detailError) }} <button type="button" class="stash-button" @click="loadMemoryDetail">{{ t('action.retry') }}</button></p><dl><div v-for="field in selectedFields" :key="field.label"><dt>{{ field.label }}</dt><dd>{{ field.value }}</dd></div></dl>
            <div v-if="selectedParent || selectedChildren.length" class="stash-related-links"><div v-if="selectedParent"><span>{{ t('view.parentTitle', { kind: kindLabel(selectedParent.kind) }) }}</span><button type="button" @click="selectObject(selectedParent.kind, selectedParent.item)">{{ itemTitle(selectedParent.kind, selectedParent.item) }}</button></div><div v-if="selectedChildren.length"><span>{{ t('view.childCount', { count: selectedChildren.length }) }}</span><div><button v-for="child in selectedChildren" :key="child.key" type="button" @click="selectObject(child.kind, child.item)">{{ itemTitle(child.kind, child.item) }}</button></div></div></div>
            <div v-if="selectedConnections.length" class="stash-related-links" :aria-label="t('view.connections')"><div v-for="connection in selectedConnections" :key="connection.key"><span>{{ connection.label }}</span><button type="button" @click="selectObject(connection.kind, connection.item)">{{ itemTitle(connection.kind, connection.item) }}</button></div></div>
          </article>

          <template v-else-if="route.route === 'goal-map'">
            <div class="stash-overview-tools">
              <label class="stash-field is-search"><span class="stash-sr-only">{{ t('action.search') }}</span><input v-model="filters.query" :placeholder="t('search.overview')" @input="syncURL"></label>
              <details class="stash-filters"><summary>{{ t('filter.label') }}<span v-if="hasFilters" class="stash-filter-dot"></span></summary><div class="stash-filter-panel">
                <label class="stash-field"><span>{{ t('field.workStatus') }}</span><select v-model="filters.status" @change="syncURL"><option value="">{{ t('filter.all') }}</option><option v-for="status in statusOptions" :key="status" :value="status">{{ statusLabel(status) }}</option></select></label>
                <label class="stash-field"><span>{{ t('field.owner') }}</span><select v-model="filters.agent" @change="syncURL"><option value="">{{ t('filter.all') }}</option><option v-for="agent in agents" :key="agent" :value="agent">{{ agent }}</option></select></label>
                <label class="stash-field"><span>{{ t('field.memoryType') }}</span><select v-model="filters.memoryType" @change="syncURL"><option value="">{{ t('filter.all') }}</option><option value="fact">{{ t('nav.facts') }}</option><option value="episode">{{ t('memory.episode') }}</option><option value="hypothesis">{{ t('nav.hypotheses') }}</option><option value="failure">{{ t('memory.failure') }}</option></select></label>
                <button type="button" class="stash-button" @click="resetFilters">{{ t('action.reset') }}</button>
              </div></details>
              <div class="stash-view-switch" :aria-label="t('view.mode')"><button type="button" :aria-pressed="mapAsList" @click="mapAsList = true">{{ t('view.list') }}</button><button type="button" :aria-pressed="!mapAsList" @click="mapAsList = false">{{ t('view.map') }}</button></div>
            </div>
            <div class="stash-kind-tabs" :aria-label="t('view.kinds')"><button type="button" :aria-pressed="activeKind === 'all'" @click="showKind('all')">{{ t('filter.all') }} <span>{{ formatNumber(rootCounts.goal + rootCounts.work + rootCounts.memory + rootCounts.resource) }}</span></button><button v-for="kind in kindOrder" :key="kind" type="button" :aria-pressed="activeKind === kind" @click="showKind(kind)">{{ kind === 'memory' ? t('view.linkedMemory') : kindNames[kind] }} <span>{{ formatNumber(rootCounts[kind]) }}</span></button></div>
            <div v-if="!mapAsList" class="stash-legend"><button type="button" class="stash-button" @click="fitMap = !fitMap">{{ fitMap ? t('view.actualSize') : t('view.fit') }}</button><span><i></i>{{ t('map.goalLink') }}</span><span><i class="is-dash"></i>{{ t('map.context') }}</span></div>
            <div v-if="!mapLayout.nodes.length" class="stash-empty"><strong>{{ hasFilters ? t('empty.filtered') : t('empty.overview') }}</strong><button v-if="hasFilters" type="button" class="stash-button" @click="resetFilters">{{ t('action.clearFilters') }}</button></div>
            <div v-else-if="mapAsList" class="stash-list"><button v-for="node in mapLayout.nodes" :key="node.key" type="button" class="stash-list-item" :class="{'is-selected': selected && selected.key === node.key}" @click="selectMapNode(node)"><span><strong>{{ nodeTitle(node) }}</strong><small v-if="node.kind === 'goal'">{{ goalProgressLabel(node.item) }}</small><small v-else-if="node.kind === 'work'">{{ workNote(node.item) }}</small></span><span class="stash-list-meta"><span>{{ kindLabel(node.kind) }}</span><span v-if="node.kind === 'work'" class="stash-status" :data-status="displayStatus(node.item)">{{ statusLabel(displayStatus(node.item)) }}</span><span v-else-if="node.kind === 'memory'">{{ memoryTypeLabel(node.item.memory_type) }}</span></span></button></div>
            <div v-else class="stash-map-viewport"><div class="stash-map-canvas" :style="canvasStyle(mapLayout)"><svg class="stash-map-edge-layer" :viewBox="'0 0 ' + mapLayout.width + ' ' + mapLayout.height" aria-hidden="true"><defs><marker id="stash-map-arrow" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0,0 L8,4 L0,8 z" fill="#818cf8"></path></marker></defs><path v-for="edge in mapLayout.edges" :key="edge.key" :d="edge.path" :stroke="edge.stroke" stroke-width="2" :stroke-dasharray="edge.dashArray || null" :marker-end="edge.marker ? 'url(#stash-map-arrow)' : null" fill="none"></path></svg><div v-for="ring in mapLayout.rings" :key="ring.key" class="stash-map-ring" :style="ring.style"><span>{{ t('map.ring.' + ring.key) }} · {{ formatNumber(ring.count) }}</span></div><button v-for="node in mapLayout.nodes" :key="node.key" type="button" class="stash-map-node" :class="mapNodeClasses(node)" :style="node.style" :aria-label="nodeAria(node)" @click="selectMapNode(node)"><span class="stash-node-meta"><span class="stash-node-key">{{ nodeKey(node) }}</span><span v-if="node.kind === 'work'" class="stash-status" :data-status="displayStatus(node.item)">{{ statusLabel(displayStatus(node.item)) }}</span><span v-else>{{ kindLabel(node.kind) }}</span></span><span class="stash-node-title">{{ nodeTitle(node) }}</span><span v-if="node.kind === 'goal'" class="stash-node-note">{{ goalProgressLabel(node.item) }}</span><span v-if="node.kind === 'work'" class="stash-node-note">{{ workNote(node.item) }}</span><span v-else-if="node.kind === 'resource'" class="stash-node-note">{{ node.item.source || t('resource.linked') }}</span><span v-else-if="node.kind === 'memory'" class="stash-node-note">{{ memoryTypeLabel(node.item.memory_type) }}</span></button></div></div>
          </template>

          <template v-else-if="route.route === 'graph'">
            <div class="stash-toolbar"><label class="stash-field is-search"><span>{{ t('action.search') }}</span><input v-model="filters.query" :placeholder="t('search.graph')" @input="syncURL"></label><label class="stash-field"><span>{{ t('field.status') }}</span><select v-model="filters.status" @change="syncURL"><option value="">{{ t('filter.allStatuses') }}</option><option v-for="status in statusOptions" :key="status" :value="status">{{ statusLabel(status) }}</option></select></label><label class="stash-field"><span>{{ t('field.owner') }}</span><select v-model="filters.agent" @change="syncURL"><option value="">{{ t('filter.allOwners') }}</option><option v-for="agent in agents" :key="agent" :value="agent">{{ agent }}</option></select></label><button type="button" class="stash-button" @click="resetFilters">{{ t('action.reset') }}</button></div><div class="stash-checks"><span>{{ t('map.relationships') }}</span><label><input type="checkbox" v-model="relations.blocks" @change="syncURL">{{ t('map.blocks') }}</label><label><input type="checkbox" v-model="relations.part_of" @change="syncURL">{{ t('map.partOf') }}</label><label><input type="checkbox" v-model="relations.relates_to" @change="syncURL">{{ t('map.related') }}</label></div><div class="stash-legend"><button type="button" class="stash-button" @click="fitMap = !fitMap">{{ fitMap ? t('view.actualSize') : t('view.fit') }}</button><span><i style="color:#e9a23b"></i>{{ t('map.blockLegend') }}</span><span><i style="color:#9b8cf2"></i>{{ t('map.parentLegend') }}</span><span><i class="is-dash"></i>{{ t('map.related') }}</span></div>
            <div v-if="!graphLayout.nodes.length" class="stash-empty"><strong>{{ t('empty.graph') }}</strong></div>
            <div v-else class="stash-graph-viewport"><div class="stash-graph-canvas" :style="canvasStyle(graphLayout)"><svg class="stash-graph-edge-layer" :viewBox="'0 0 ' + graphLayout.width + ' ' + graphLayout.height" aria-hidden="true"><defs><marker id="stash-graph-arrow" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0,0 L8,4 L0,8 z" fill="#e9a23b"></path></marker></defs><path v-for="edge in graphLayout.edges" :key="edge.key" :d="edge.path" :stroke="edge.stroke" stroke-width="2" :stroke-dasharray="edge.dashArray || null" :marker-end="edge.marker ? 'url(#stash-graph-arrow)' : null" fill="none"></path></svg><button v-for="node in graphLayout.nodes" :key="node.key" type="button" class="stash-graph-node" :class="{'is-selected': selected && selected.key === node.key}" :style="node.style" @click="selectGraphNode(node)"><span class="stash-node-meta"><span class="stash-node-key">{{ node.item.issue_key || '#' + node.item.id }}</span><span class="stash-status" :data-status="displayStatus(node.item)">{{ statusLabel(displayStatus(node.item)) }}</span></span><span class="stash-node-title">{{ node.item.title }}</span><span class="stash-node-note">{{ workNote(node.item) }}</span></button></div></div>
          </template>

          <template v-else-if="route.route === 'monitor'">
            <div class="stash-toolbar"><label class="stash-field is-search"><span>{{ t('action.search') }}</span><input v-model="filters.query" :placeholder="t('search.monitor')" @input="syncURL"></label><label class="stash-field"><span>{{ t('field.status') }}</span><select v-model="filters.status" @change="syncURL"><option value="">{{ t('filter.allStatuses') }}</option><option v-for="status in statusOptions" :key="status" :value="status">{{ statusLabel(status) }}</option></select></label><label class="stash-field"><span>{{ t('field.owner') }}</span><select v-model="filters.agent" @change="syncURL"><option value="">{{ t('filter.allOwners') }}</option><option v-for="agent in agents" :key="agent" :value="agent">{{ agent }}</option></select></label><button type="button" class="stash-button" @click="resetFilters">{{ t('action.reset') }}</button></div><div class="stash-list"><button v-for="item in monitorRows" :key="item.id" type="button" class="stash-list-item" :class="{'is-selected': selected && selected.key === mapItemKey('work', item)}" @click="selectObject('work', item)"><span><strong>{{ item.issue_key || '#' + item.id }} · {{ item.title }}</strong><small>{{ workNote(item) }}</small></span><span class="stash-list-meta"><span class="stash-status" :data-status="displayStatus(item)">{{ statusLabel(displayStatus(item)) }}</span><span>{{ agentLabel(item) }}</span></span></button><div v-if="!monitorRows.length" class="stash-empty"><strong>{{ t('empty.work') }}</strong></div></div>
          </template>

          <template v-else-if="route.route === 'board'">
            <div class="stash-toolbar"><label class="stash-field is-search"><span>{{ t('action.search') }}</span><input v-model="filters.query" :placeholder="t('search.work')" @input="syncURL" @keydown.enter="searchList"></label><label class="stash-field"><span>{{ t('field.type') }}</span><select v-model="filters.issueType" @change="searchList"><option value="">{{ t('filter.allTypes') }}</option><option value="task">{{ t('kind.work') }}</option><option value="bug">{{ t('issue.bug') }}</option><option value="feature">{{ t('issue.feature') }}</option><option value="chore">{{ t('issue.chore') }}</option><option value="question">{{ t('issue.question') }}</option></select></label><label class="stash-field"><span>{{ t('field.label') }}</span><input v-model="filters.label" :placeholder="t('field.label')" @input="syncURL" @keydown.enter="searchList"></label><button type="button" class="stash-button" @click="searchList">{{ t('action.search') }}</button><button type="button" class="stash-button" @click="resetFilters">{{ t('action.reset') }}</button></div><div v-if="!boardItems.length" class="stash-empty"><strong>{{ t('empty.work') }}</strong></div><div v-else class="stash-plan-grid"><div v-for="column in boardColumns" :key="column.status" class="stash-plan-component"><header><h3>{{ statusLabel(column.status) }}</h3><span class="stash-status" :data-status="column.status">{{ formatNumber(column.items.length) }}</span></header><ul class="stash-plan-tasks"><li v-for="item in column.items" :key="item.id" class="stash-plan-task"><button type="button" @click="selectObject('work', item)"><strong>{{ item.issue_key || '#' + item.id }}</strong> {{ item.title }}</button><small>{{ agentLabel(item) }}</small></li><li v-if="!column.items.length" class="stash-plan-task"><small>{{ t('empty.none') }}</small></li></ul></div></div>
          </template>

          <template v-else-if="route.route === 'plan'">
            <div v-if="planRootGoal" class="stash-plan-goal"><span>{{ t('plan.sharedGoal') }}</span><strong>{{ planRootGoal.content }}</strong><span class="stash-status">{{ goalProgressLabel(planRootGoal) }}</span></div><div v-if="plan.warnings.length || (plan.validation && (!plan.validation.passed || plan.validation.stale))" class="stash-context-note">{{ plan.warnings.length ? t('plan.warningCount', { count: plan.warnings.length }) + ' ' : '' }}{{ plan.validation && plan.validation.stale ? t('plan.stale') : plan.validation && !plan.validation.passed ? t('plan.reviewFailed') : '' }}</div><div v-if="!plan.components.length" class="stash-empty"><strong>{{ t('empty.plan') }}</strong></div><div v-else class="stash-plan-grid"><article v-for="component in plan.components" :key="component.id" class="stash-plan-component"><header><div><h3><button type="button" class="stash-plan-title" @click="selectObject('work', component)">{{ component.issue_key || '#' + component.id }} · {{ component.title }}</button></h3><p v-if="component.execution_progress">{{ componentProgressLabel(component) }}</p><p>{{ component.description || t('empty.conditions') }}</p></div><span class="stash-status" :data-status="displayStatus(component)">{{ statusLabel(displayStatus(component)) }}</span></header><ul class="stash-plan-tasks"><li v-for="task in component.tasks || []" :key="task.id" class="stash-plan-task"><button type="button" @click="selectObject('work', task)"><strong>{{ task.issue_key || '#' + task.id }}</strong> {{ task.title }}</button><small>{{ statusLabel(task.status) }}</small></li><li v-if="!(component.tasks || []).length" class="stash-plan-task"><small>{{ t('empty.children') }}</small></li></ul></article></div><div v-if="plan.decisions.length" class="stash-plan-decisions"><div v-for="decision in plan.decisions" :key="decision.id" class="stash-plan-decision"><strong>{{ decision.title }}</strong><div>{{ decision.rationale }}</div></div></div>
          </template>

          <template v-else-if="isListRoute">
            <div class="stash-toolbar"><label class="stash-field is-search"><span>{{ t('action.search') }}</span><input v-model="filters.query" :placeholder="listPlaceholder" @input="syncURL" @keydown.enter="searchList"></label><label v-if="route.route === 'list_memories'" class="stash-field"><span>{{ t('field.type') }}</span><select v-model="filters.memoryType" @change="filters.status = ''; searchList()"><option value="">{{ t('filter.all') }}</option><option value="fact">{{ t('nav.facts') }}</option><option value="episode">{{ t('memory.episode') }}</option><option value="hypothesis">{{ t('nav.hypotheses') }}</option><option value="failure">{{ t('memory.failure') }}</option></select></label><label v-if="statusOptions.length" class="stash-field"><span>{{ t('field.status') }}</span><select v-model="filters.status" @change="searchList"><option value="">{{ t('filter.allStatuses') }}</option><option v-for="status in statusOptions" :key="status" :value="status">{{ statusLabel(status) }}</option></select></label><button type="button" class="stash-button" @click="searchList">{{ t('action.search') }}</button></div><div class="stash-list"><button v-for="item in visibleListItems" :key="listItemKey(item)" type="button" class="stash-list-item" :class="{'is-selected': selected && selected.key === listItemKey(item)}" @click="selectListItem(item)"><span><strong>{{ listItemTitle(item) }}</strong><small>{{ listItemSummary(item) }}</small></span><span class="stash-list-meta"><span v-if="listKind === 'memory'">{{ memoryTypeLabel(item.memory_type) }}</span><span v-if="item.status && (listKind !== 'memory' || item.memory_type === 'hypothesis')" class="stash-status" :data-status="item.status">{{ statusLabel(item.status) }}</span><span v-if="item.slug && route.route !== 'list_namespaces'">{{ item.slug }}</span></span></button><div v-if="!visibleListItems.length" class="stash-empty"><strong>{{ t('empty.items') }}</strong></div></div>
          </template>

          <template v-else-if="route.route === 'agent'"><div class="stash-guide"><button type="button" class="stash-button" @click="copyAgentGuide">{{ t(copyStatus) }}</button><details><summary>{{ t('agent.allRules') }}</summary><textarea :aria-label="t('agent.rulesLabel')" readonly :value="agentGuide"></textarea></details></div></template>
          <template v-else-if="route.route === 'maintenance' && maintenance"><div class="stash-guide"><dl class="stash-maintenance-counts"><div><dt>{{ t('maintenance.pending') }}</dt><dd>{{ formatNumber(maintenance.pending || 0) }}</dd></div><div><dt>{{ t('maintenance.due') }}</dt><dd>{{ formatNumber(maintenance.due || 0) }}</dd></div><div><dt>{{ t('maintenance.failed') }}</dt><dd>{{ formatNumber(maintenance.failed || 0) }}</dd></div><div><dt>{{ t('maintenance.paused') }}</dt><dd>{{ formatNumber(maintenance.paused || 0) }}</dd></div></dl><div class="stash-top-actions"><button type="button" class="stash-button" :disabled="maintenanceAction" @click="runMaintenance('retry')">{{ t('maintenance.retry') }}</button><button type="button" class="stash-button" :disabled="maintenanceAction" @click="runMaintenance('reindex')">{{ t('maintenance.reindex') }}</button></div><p v-if="maintenanceNotice" role="status">{{ t(maintenanceNotice) }}</p><details v-if="maintenance.latest_error"><summary>{{ t('maintenance.latestError') }}</summary><p>{{ maintenance.latest_error }}</p></details></div></template>
          <template v-else><div class="stash-empty"><strong>{{ staticTitle }}</strong><span>{{ staticText }}</span></div></template>
          <div v-if="(isListRoute && route.route !== 'list_namespaces') || route.route === 'board'" class="stash-pagination"><span>{{ t('view.shownCount', { count: listItems.length }) }}</span><button v-if="route.offset" type="button" class="stash-button" @click="searchList">{{ t('action.firstPage') }}</button><button v-if="page.hasMore" type="button" class="stash-button" @click="nextPage">{{ t('action.more') }}</button></div>
        </section>

        <aside v-if="selected && !route.detail" class="stash-inspector" tabindex="-1" :aria-label="t('view.selection')">
          <div class="stash-inspector-head"><div><p class="stash-kicker">{{ kindLabel(selected.kind) }}</p><h3>{{ selectedTitle }}</h3></div><button type="button" :aria-label="t('action.closeSelection')" @click="clearSelection">×</button></div>
          <dl><div v-for="field in selectedFields.slice(0, 6)" :key="field.label"><dt>{{ field.label }}</dt><dd>{{ field.value }}</dd></div></dl>
          <div v-if="selectedParent || selectedChildren.length" class="stash-related-links"><div v-if="selectedParent"><span>{{ t('view.parentTitle', { kind: kindLabel(selectedParent.kind) }) }}</span><button type="button" @click="selectObject(selectedParent.kind, selectedParent.item)">{{ itemTitle(selectedParent.kind, selectedParent.item) }}</button></div><div v-if="selectedChildren.length"><span>{{ t('view.childCount', { count: selectedChildren.length }) }}</span><div><button v-for="child in selectedChildren" :key="child.key" type="button" @click="selectObject(child.kind, child.item)">{{ itemTitle(child.kind, child.item) }}</button></div></div></div>
          <div v-if="selectedConnections.length" class="stash-related-links" :aria-label="t('view.connections')"><div v-for="connection in selectedConnections" :key="connection.key"><span>{{ connection.label }}</span><button type="button" @click="selectObject(connection.kind, connection.item)">{{ itemTitle(connection.kind, connection.item) }}</button></div></div>
          <div class="stash-inspector-actions"><button type="button" class="stash-button is-primary" @click="openDetail">{{ t('action.details') }}</button><a v-if="selected.kind === 'work'" class="stash-button" :href="issueHref(selected.item)">{{ t('action.showBoard') }}</a></div>
        </aside>
      </div>
    </section>
  </main>
</div>`;

    const viewModel = root.StashVueConsoleViewModel.createViewModel({
        api: root.StashApiClient.createApiClient(),
        routeAPI: root.StashRouteState,
        goalMap: root.StashGoalMap,
        workGraph: root.StashWorkGraph,
        search: root.StashSearch,
        i18n: root.StashI18n,
        window: root
    });
    let selectionTrigger = null;
    const focusSelection = function () {
        this.$nextTick(() => {
            const target = document.querySelector(this.route.detail ? '.stash-detail' : '.stash-inspector');
            if (target) target.focus();
        });
    };
    root.StashVueRuntime.createApp({ ...viewModel, template, watch: {
        selected(next, previous) {
            if (next && !previous) selectionTrigger = document.activeElement;
            if (next) focusSelection.call(this);
            else if (selectionTrigger && selectionTrigger.isConnected) selectionTrigger.focus();
        },
        'route.detail': focusSelection
    } })
        .mount(document.querySelector('[data-stash-vue-console]'));
}(typeof globalThis !== 'undefined' ? globalThis : window));
